In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as st
import numpy as np

In [2]:
# Study data files
lck = "spring_2021/lck_spring_2021.csv"
lec = "spring_2021/lec_spring_2021.csv"
lpl= "spring_2021/lpl_spring_2021.csv"
lcs= "spring_2021/lcs_spring_2021.csv"
region = "spring_2021/region_games_2021.csv"
total = "spring_2021/total_data_2021.csv"
min_d = "spring_2021/min_diversity_2021.csv"
max_d = "spring_2021/max_diversity_2021.csv"

#read data into dfs
lck_data = pd.read_csv(lck)
lec_data = pd.read_csv(lec, encoding = "ISO-8859-1")
lpl_data = pd.read_csv(lpl)
lcs_data = pd.read_csv(lcs)
min_diversity = pd.read_csv(min_d)
max_diversity = pd.read_csv(max_d)
region_data = pd.read_csv(region)
# total_data = pd.read_csv(total)

In [3]:
#cleaning data
lck_data['Presence']=pd.to_numeric(lck_data['Presence'].str.replace('%',''))
lcs_data['Presence']=pd.to_numeric(lcs_data['Presence'].str.replace('%',''))
lec_data['Presence']=pd.to_numeric(lec_data['Presence'].str.replace('%',''))
lpl_data['Presence']=pd.to_numeric(lpl_data['Presence'].str.replace('%',''))

In [4]:
#cleaning data
lck_data['Winrate']=pd.to_numeric(lck_data['Winrate'].str.replace('%',''))
lcs_data['Winrate']=pd.to_numeric(lcs_data['Winrate'].str.replace('%',''))
lec_data['Winrate']=pd.to_numeric(lec_data['Winrate'].str.replace('%',''))
lpl_data['Winrate']=pd.to_numeric(lpl_data['Winrate'].str.replace('%',''))

In [5]:
region_data

  region  total_games
0    LCK          215
1    LCS           90
2    LEC           90
3    LPL          306

In [6]:
#recalculate the presence column for more exact nubmers
lck_data['True Presence']= (lck_data['Picks']+lck_data['Bans'])/region_data['total_games'][0]*100
lcs_data['True Presence']= (lcs_data['Picks']+lcs_data['Bans'])/region_data['total_games'][1]*100
lec_data['True Presence']= (lec_data['Picks']+lec_data['Bans'])/region_data['total_games'][2]*100
lpl_data['True Presence']= (lpl_data['Picks']+lpl_data['Bans'])/region_data['total_games'][3]*100

In [7]:
#export cleaned df to csv
lck_data.to_csv('spring_2021/cleaned/lck_data_2021.csv')
lcs_data.to_csv('spring_2021/cleaned/lcs_data_2021.csv')
lec_data.to_csv('spring_2021/cleaned/lec_data_2021.csv')
lpl_data.to_csv('spring_2021/cleaned/lpl_data_2021.csv')

In [8]:
#set index to 'champion' column so we don't have index column when we import the tables to html
lck_data=lck_data.set_index('Champion')
lec_data=lec_data.set_index('Champion')
lpl_data=lpl_data.set_index('Champion')
lcs_data=lcs_data.set_index('Champion')

In [9]:
#dfs in html format
# lck_data.to_html('raw_data_html/lck_data_.html')
# lcs_data.to_html('raw_data_html/lcs_data.html')
# lec_data.to_html('raw_data_html/lec_data.html')
# lpl_data.to_html('raw_data_html/lpl_data.html')

In [10]:
from functools import reduce

In [11]:
#join all the tables so I can calculate the champion presence for all the regions combined
data_frames=[lck_data,lcs_data,lpl_data,lec_data]
total_data = reduce(lambda  left,right: pd.merge(left,right,on=['Champion'],
                                            how='outer'), data_frames)

In [12]:
total_data

,Picks_x,Bans_x,Presence_x,Wins_x,Losses_x,Winrate_x,KDA_x,Avg BT_x,GT_x,CSM_x,...,KDA_y,Avg BT_y,GT_y,CSM_y,DPM_y,GPM_y,CSD@15_y,GD@15_y,XPD@15_y,True Presence_y
Champion,,,,,,,,,,,,,,,,,,,,,
Gnar,81,112,90,36.0,45.0,44.0,2.3,5.8,33:28:00,8.1,...,3.4,8.5,32:22:00,8.0,515.0,381.0,7.8,168.0,114.0,50.000000
Kaisa,153,35,87,71.0,82.0,46.0,3.7,5.3,33:13:00,9.7,...,3.9,4.6,32:39:00,9.4,472.0,443.0,2.8,-118.0,160.0,83.333333
Renekton,56,121,82,32.0,24.0,57.0,3.3,4.3,32:24:00,8.5,...,2.7,5.7,34:00:00,8.1,362.0,376.0,7.8,260.0,91.0,70.000000
Rell,82,90,80,38.0,44.0,46.0,2.4,5,32:23:00,1.2,...,2.7,5.5,32:16:00,1.1,145.0,236.0,1.3,-49.0,-94.0,76.666667
Udyr,66,84,70,35.0,31.0,53.0,4.7,4,33:30:00,6.3,...,2.9,3.8,33:05:00,6.1,188.0,329.0,2.6,-53.0,16.0,74.444444
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Bard,0,0,0,NaN,NaN,NaN,NaN,-,0:00,NaN,...,1,-,42:41:00,1.3,223.0,207.0,18.0,-560.0,-496.0,1.111111
Illaoi,0,0,0,NaN,NaN,NaN,NaN,-,0:00,NaN,...,NaN,-,0:00,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
Aurelion Sol,0,0,0,NaN,NaN,NaN,NaN,-,0:00,NaN,...,NaN,-,0:00,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
Ivern,0,0,0,NaN,NaN,NaN,NaN,-,0:00,NaN,...,5.3,-,29:51:00,6.2,213.0,313.0,-9.7,-630.0,-336.0,3.333333
Qiyana,0,0,0,NaN,NaN,NaN,NaN,-,0:00,NaN,...,1.8,-,27:24:00,6.7,503.0,378.0,-40.0,-88.0,-822.0,1.111111

In [13]:
pd.DataFrame.to_csv(total_data, 'spring_2021/total_data_2021.csv', index=True)

In [14]:
#cleaned the total data in excel, easier that way